INSERT INTO Categories (parent_cate, cate_name) VALUES
(NULL, 'Root'),
('Root','Patio & Garden'),
('Patio & Garden','Indoor & Live Plants'),
('Indoor & Live Plants','Plant Gifts'),
('Indoor & Live Plants','Indoor Plants'),
('Indoor & Live Plants','Annuals'),
('Patio & Garden','Outdoor Decor'),
('Outdoor Decor','Outdoor Cushions'),
('Outdoor Decor','Outdoor Lighting'),
('Patio & Garden','Patio Furniture'),
('Patio Furniture','Patio Conversation Sets'),
('Patio Furniture','Patio Dining Sets'),
('Patio Furniture','Porch Swings'),
('Root','Pets'),
('Pets','Cat '),
('Cat ','Cat Dry Food'),
('Cat ','Cat Wet Food'),
('Cat ','Climbing Trees'),
('Pets','Dog'),
('Dog','Dog Beds'),
('Dog','Dog Dry Food'),
('Dog','Dog Wet Food'),
('Root','Pharmacy & Health & Wellness'),
('Pharmacy & Health & Wellness','Wellness'),
('Wellness','Sleep Support'),
('Wellness','Weight Loss'),
('Wellness','Performance Nutrition'),
('Pharmacy & Health & Wellness','Health Care'),
('Health Care','Pain Relievers'),
('Health Care','Cough & Cold & Flu'),
('Health Care','Eye Care'),
('Root','Clothing'),
('Clothing','Tops'),
('Tops','T-Shirts'),
('Tops','Long Sleeves'),
('Tops','Bodysuits'),
('Clothing','Bottoms'),
('Bottoms','Skirts'),
('Bottoms','Pants'),
('Bottoms','Jeans'),
('Clothing','Sleepwear'),
('Sleepwear','Bath Robes'),
('Root','Beauty Products'),
('Beauty Products','Makeup'),
('Makeup','Lip'),
('Makeup','Face'),
('Makeup','Brushes & Applicators'),
('Root','Electrical Supplies'),
('Electrical Supplies','Wearable Technology'),
('Wearable Technology','Headphones'),
('Wearable Technology','Apple Watch'),
('Wearable Technology','Wireless Headphones'),
('Electrical Supplies','Cell Phones'),
('Cell Phones','Samsung'),
('Cell Phones','Iphone'),
('Electrical Supplies','Tv & Home Theater'),
('Tv & Home Theater','55-Inch Tvs'),
('Tv & Home Theater','65-Inch Tvs'),
('Tv & Home Theater','75-Inch Tvs'),
('Root','Grocery'),
('Grocery','Bakery & Bread'),
('Bakery & Bread','Pies'),
('Bakery & Bread','Cookies & Brownies'),
('Bakery & Bread','Rolls & Buns'),
('Grocery','Fresh Produce'),
('Grocery','Meat & Seafood'),
('Meat & Seafood','Beef & Lamb'),
('Meat & Seafood','Pork'),
('Meat & Seafood','Seafood'),
('Root','Kitchen & Appliances'),
('Kitchen & Appliances','Kitchen & Cooking Accessories'),
('Kitchen & Cooking Accessories','Kitchen Utensils'),
('Kitchen & Cooking Accessories','Cooking Accessories'),
('Kitchen & Cooking Accessories','Mixing & Measuring Tools'),
('Kitchen & Appliances','Kitchen Cabinets'),
('Kitchen Cabinets','Base Cabinets'),
('Kitchen Cabinets','Wall Cabinets'),
('Kitchen Cabinets','High Cabinets'),
('Kitchen & Appliances','Kitchen Faucets & Sinks'),
('Kitchen Faucets & Sinks','Kitchen Faucets'),
('Kitchen Faucets & Sinks','Kitchen Sinks'),
('Root','Toys & Video Games '),
('Toys & Video Games ','Video Games'),
('Video Games','Playstation'),
('Toys & Video Games ','Outdoor Play'),
('Toys & Video Games ','Toys'),
('Toys','Kidkraft Bancroft Wooden Playhouse'),
('Root','Sports & Outdoors'),
('Sports & Outdoors','Exercise & Fitness'),
('Exercise & Fitness','Exercise Machines'),
('Exercise & Fitness','Boxing & Mma'),
('Exercise & Fitness','Yoga'),
('Sports & Outdoors','Bikes'),
('Bikes','Mountain'),
('Bikes','Electric'),
('Sports & Outdoors','Sports'),
('Sports','Baseball'),
('Sports','Basketball'),
('Sports','Tennis');
